# Generated by Django 5.0.8 on 2024-10-14 22:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admission', '0002_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='intake',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admission.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intake',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intake',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
    ]
